CREATE DATABASE TODOSAPP;

USE TODOSAPP;

CREATE TABLE tasks(
	id INT NOT NULL AUTO_INCREMENT,
    descripcion VARCHAR(50) NOT NULL,
    completed BOOL DEFAULT FALSE NOT NULL,
    dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dateEdited TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
 );